### ISSUE TITLE
Instructor Checklist

### ISSUE THREAD

**Issue by itcarroll** [cmu-lib/2019-06-04-carnegie#1]
**Before the workshop, instructors will**

- [x] Decide on the order of the lessons and who will teach what modules
- [x] Set up the workshop website using the [workshop template](https://github.com/carpentries/workshop-template) and send to the Carpentries Workshop Administration Team.  Detailed instructions are in this repo's [README](https://github.com/carpentries/workshop-template#workshop-template).
- [ ] Create an [Etherpad](https://pad.carpentries.org/) for the workshop (Ian)
- [x] Assist the host in recruiting helpers if possible (Ryan)
- [x] Assist the host in ensuring the workshop location is accessible (Ryan)
- [x] Share emergency contact information with host in case of last minute changes (Ryan)
- [ ] Practice teaching the material (Ian + Ryan)
- [x] Confirm criteria for reimbursement (*per diem* or save receipts)

**During the workshop instructors will**

- [ ] Review Code of Conduct with learners (Ryan)
- [ ] Remind learners to use sticky notes to give feedback (Ian)
- [ ] Get feedback at lunch and end of each day using minute cards (Ian)

**After the workshop instructors will**

- [ ] Remind the host to send workshop attendance data to the Carpentries Workshop Administration Team (Ian)
- [ ] Submit receipts for reimbursement
- [ ] Send their own feedback to the Workshop Administration Team including any configuration problems
- [ ] Take part in a [community discussion](https://pad.carpentries.org/community-discussions)
- [ ] Report any lesson errors or suggest improvements on GitHub or by email to the Carpentries Workshop Administration Team

**Comment by rkclement** [comment]
Hi Ian --

This is my first workshop as a non-host (previously I had been a co-instructor but was also hosting, organizing, etc.). How do you want to divide up this checklist? My semester here is basically over now, so I've got more time to work on this.
